const chat=document.getElementById("chat"),form=document.getElementById("chatForm"),input=document.getElementById("message"),leads=[];
const replies=[["fee","Our NEET and JEE programs start from ₹18,000. Scholarships may be available based on the entrance test."],["course","We offer NEET, JEE, Foundation and CUET preparation. Which course are you interested in?"],["batch","New batches start in January, April and July. I can have an admissions counsellor share the current timetable."],["time","Counsellors are available from 9 AM to 7 PM, Monday to Saturday."],["location","Our centre is near the main city campus. I can have the team share the exact location and directions."],["admission","Absolutely. Please share your name, phone number and preferred course below so our admissions team can contact you."]];
function add(text,who){const d=document.createElement("div");d.className="bubble "+who;d.textContent=text;chat.appendChild(d);chat.scrollTop=chat.scrollHeight}
function reply(text){const t=text.toLowerCase(),hit=replies.find(x=>t.includes(x[0]));return hit?hit[1]:"I can help with courses, fees, batches, timings, location and admissions. What would you like to know?"}
function send(text){if(!text.trim())return;add(text,"user");setTimeout(()=>add(reply(text),"bot"),350)}
form.addEventListener("submit",e=>{e.preventDefault();send(input.value);input.value=""});
document.querySelectorAll(".quick button").forEach(b=>b.onclick=()=>send(b.dataset.q));
document.getElementById("leadForm").addEventListener("submit",e=>{e.preventDefault();leads.unshift({name:document.getElementById("name").value,phone:document.getElementById("phone").value,course:document.getElementById("course").value});renderLeads();document.getElementById("saved").textContent="✓ Lead captured successfully";e.target.reset()});
function renderLeads(){const box=document.getElementById("leads");document.getElementById("leadCount").textContent=leads.length+" lead"+(leads.length===1?"":"s");box.className="";box.innerHTML=leads.map(l=>"<div class='lead-row'><b>"+escapeHtml(l.name)+"</b><span>"+escapeHtml(l.phone)+"</span><span>"+escapeHtml(l.course)+"</span><small>New lead</small></div>").join("")}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}